"""add video_shots table

Revision ID: 77df30935788
Revises: 0018_eval_runs_baseline
Create Date: 2026-09-09 02:51:38.409165

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77df30935788"
down_revision: str | Sequence[str] | None = "0018_eval_runs_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_shots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("kb_id", sa.String(length=64), nullable=False),
        sa.Column("shot_index", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("keyframe_path", sa.String(length=1024), nullable=True),
        sa.Column("asr_text", sa.Text(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("caption_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_id", "shot_index", name="uq_video_shots_doc_shot"),
    )
    with op.batch_alter_table("video_shots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_video_shots_caption_status"), ["caption_status"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_shots_doc_id"), ["doc_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_video_shots_kb_id"), ["kb_id"], unique=False)

    # NOTE: autogen also proposed a documents.content_hash TEXT→String(64)
    # type alter — pre-existing drift unrelated to this revision, dropped to
    # keep the migration atomic (video_shots only).

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("video_shots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_shots_kb_id"))
        batch_op.drop_index(batch_op.f("ix_video_shots_doc_id"))
        batch_op.drop_index(batch_op.f("ix_video_shots_caption_status"))

    op.drop_table("video_shots")
    # ### end Alembic commands ###
